import { CampaniaMonthResult } from "@/Interfaces/CampaniaMonthResult";

export const MONTHS = [
    "Enero",
    "Febrero",
    "Marzo",
    "Abril",
    "Mayo",
    "Junio",
    "Julio",
    "Agosto",
    "Septiembre",
    "Octubre",
    "Noviembre",
    "Diciembre",
];

export const campains = [
    {
        id: 1,
        nombre: "Campaña de prueba 1",
        n_registros: 123,
        n_validados: 78,
        n_abiertos: 67,
        fecha_envio: "2024-01-01",
        medio_envio: 0,
    },
    {
        id: 2,
        nombre: "Campaña de prueba 2",
        n_registros: 59,
        n_validados: 37,
        n_abiertos: 22,
        fecha_envio: "2024-02-12",
        medio_envio: 0,
    },
    {
        id: 3,
        nombre: "Campaña de prueba 3",
        n_registros: 187,
        n_validados: 120,
        n_abiertos: 102,
        fecha_envio: "2024-03-25",
        medio_envio: 0,
    },
    {
        id: 4,
        nombre: "Campaña de prueba 4",
        n_registros: 82,
        n_validados: 57,
        n_abiertos: 35,
        fecha_envio: "2024-04-30",
        medio_envio: 0,
    },
    {
        id: 5,
        nombre: "Campaña de prueba 5",
        n_registros: 175,
        n_validados: 98,
        n_abiertos: 80,
        fecha_envio: "2024-05-17",
        medio_envio: 0,
    },
    {
        id: 6,
        nombre: "Campaña de prueba 6",
        n_registros: 33,
        n_validados: 20,
        n_abiertos: 14,
        fecha_envio: "2024-06-04",
        medio_envio: 0,
    },
    {
        id: 7,
        nombre: "Campaña de prueba 7",
        n_registros: 194,
        n_validados: 140,
        n_abiertos: 123,
        fecha_envio: "2024-07-20",
        medio_envio: 0,
    },
    {
        id: 8,
        nombre: "Campaña de prueba 8",
        n_registros: 91,
        n_validados: 72,
        n_abiertos: 65,
        fecha_envio: "2024-08-14",
        medio_envio: 0,
    },
    {
        id: 9,
        nombre: "Campaña de prueba 9",
        n_registros: 118,
        n_validados: 76,
        n_abiertos: 59,
        fecha_envio: "2024-09-09",
        medio_envio: 0,
    },
    {
        id: 10,
        nombre: "Campaña de prueba 10",
        n_registros: 45,
        n_validados: 27,
        n_abiertos: 15,
        fecha_envio: "2024-10-28",
        medio_envio: 0,
    },
    {
        id: 11,
        nombre: "Campaña de prueba 11",
        n_registros: 63,
        n_validados: 44,
        n_abiertos: 29,
        fecha_envio: "2024-11-05",
        medio_envio: 0,
    },
    {
        id: 12,
        nombre: "Campaña de prueba 12",
        n_registros: 99,
        n_validados: 70,
        n_abiertos: 58,
        fecha_envio: "2024-12-19",
        medio_envio: 0,
    },
    {
        id: 13,
        nombre: "Campaña de prueba 13",
        n_registros: 153,
        n_validados: 111,
        n_abiertos: 95,
        fecha_envio: "2024-01-23",
        medio_envio: 0,
    },
    {
        id: 14,
        nombre: "Campaña de prueba 14",
        n_registros: 24,
        n_validados: 17,
        n_abiertos: 9,
        fecha_envio: "2024-02-10",
        medio_envio: 0,
    },
    {
        id: 15,
        nombre: "Campaña de prueba 15",
        n_registros: 87,
        n_validados: 53,
        n_abiertos: 43,
        fecha_envio: "2024-03-02",
        medio_envio: 0,
    },
    {
        id: 16,
        nombre: "Campaña de prueba 16",
        n_registros: 134,
        n_validados: 82,
        n_abiertos: 75,
        fecha_envio: "2024-04-14",
        medio_envio: 0,
    },
    {
        id: 17,
        nombre: "Campaña de prueba 17",
        n_registros: 37,
        n_validados: 19,
        n_abiertos: 8,
        fecha_envio: "2024-05-30",
        medio_envio: 0,
    },
    {
        id: 18,
        nombre: "Campaña de prueba 18",
        n_registros: 171,
        n_validados: 102,
        n_abiertos: 84,
        fecha_envio: "2024-06-22",
        medio_envio: 0,
    },
    {
        id: 19,
        nombre: "Campaña de prueba 19",
        n_registros: 76,
        n_validados: 52,
        n_abiertos: 40,
        fecha_envio: "2024-07-07",
        medio_envio: 0,
    },
    {
        id: 20,
        nombre: "Campaña de prueba 20",
        n_registros: 109,
        n_validados: 81,
        n_abiertos: 64,
        fecha_envio: "2024-08-31",
        medio_envio: 0,
    },
    {
        id: 21,
        nombre: "Campaña de prueba 21",
        n_registros: 88,
        n_validados: 54,
        n_abiertos: 39,
        fecha_envio: "2024-09-22",
        medio_envio: 0,
    },
    {
        id: 22,
        nombre: "Campaña de prueba 22",
        n_registros: 175,
        n_validados: 113,
        n_abiertos: 97,
        fecha_envio: "2024-10-09",
        medio_envio: 0,
    },
    {
        id: 23,
        nombre: "Campaña de prueba 23",
        n_registros: 42,
        n_validados: 26,
        n_abiertos: 14,
        fecha_envio: "2024-11-15",
        medio_envio: 0,
    },
    {
        id: 24,
        nombre: "Campaña de prueba 24",
        n_registros: 93,
        n_validados: 65,
        n_abiertos: 55,
        fecha_envio: "2024-12-01",
        medio_envio: 0,
    },
    {
        id: 25,
        nombre: "Campaña de prueba 25",
        n_registros: 147,
        n_validados: 85,
        n_abiertos: 77,
        fecha_envio: "2024-01-28",
        medio_envio: 0,
    },
    {
        id: 26,
        nombre: "Campaña de prueba 26",
        n_registros: 29,
        n_validados: 16,
        n_abiertos: 9,
        fecha_envio: "2024-02-11",
        medio_envio: 0,
    },
    {
        id: 27,
        nombre: "Campaña de prueba 27",
        n_registros: 68,
        n_validados: 45,
        n_abiertos: 35,
        fecha_envio: "2024-03-19",
        medio_envio: 0,
    },
    {
        id: 28,
        nombre: "Campaña de prueba 28",
        n_registros: 119,
        n_validados: 72,
        n_abiertos: 60,
        fecha_envio: "2024-04-05",
        medio_envio: 0,
    },
    {
        id: 29,
        nombre: "Campaña de prueba 29",
        n_registros: 53,
        n_validados: 35,
        n_abiertos: 21,
        fecha_envio: "2024-05-20",
        medio_envio: 0,
    },
    {
        id: 30,
        nombre: "Campaña de prueba 30",
        n_registros: 180,
        n_validados: 120,
        n_abiertos: 105,
        fecha_envio: "2024-06-13",
        medio_envio: 0,
    },
    {
        id: 31,
        nombre: "Campaña de prueba 31",
        n_registros: 67,
        n_validados: 43,
        n_abiertos: 35,
        fecha_envio: "2024-07-25",
        medio_envio: 0,
    },
    {
        id: 32,
        nombre: "Campaña de prueba 32",
        n_registros: 128,
        n_validados: 89,
        n_abiertos: 70,
        fecha_envio: "2024-08-18",
        medio_envio: 0,
    },
    {
        id: 33,
        nombre: "Campaña de prueba 33",
        n_registros: 41,
        n_validados: 23,
        n_abiertos: 17,
        fecha_envio: "2024-09-04",
        medio_envio: 0,
    },
    {
        id: 34,
        nombre: "Campaña de prueba 34",
        n_registros: 97,
        n_validados: 66,
        n_abiertos: 49,
        fecha_envio: "2024-10-27",
        medio_envio: 0,
    },
    {
        id: 35,
        nombre: "Campaña de prueba 35",
        n_registros: 139,
        n_validados: 92,
        n_abiertos: 85,
        fecha_envio: "2024-11-10",
        medio_envio: 0,
    },
    {
        id: 36,
        nombre: "Campaña de prueba 36",
        n_registros: 75,
        n_validados: 47,
        n_abiertos: 38,
        fecha_envio: "2024-12-29",
        medio_envio: 0,
    },
    {
        id: 37,
        nombre: "Campaña de prueba 37",
        n_registros: 150,
        n_validados: 105,
        n_abiertos: 87,
        fecha_envio: "2024-01-14",
        medio_envio: 0,
    },
    {
        id: 38,
        nombre: "Campaña de prueba 38",
        n_registros: 21,
        n_validados: 14,
        n_abiertos: 8,
        fecha_envio: "2024-02-06",
        medio_envio: 0,
    },
    {
        id: 39,
        nombre: "Campaña de prueba 39",
        n_registros: 63,
        n_validados: 41,
        n_abiertos: 31,
        fecha_envio: "2024-03-24",
        medio_envio: 0,
    },
    {
        id: 40,
        nombre: "Campaña de prueba 40",
        n_registros: 104,
        n_validados: 68,
        n_abiertos: 51,
        fecha_envio: "2024-04-17",
        medio_envio: 0,
    },
];

export const data: CampaniaMonthResult[] = [
    {
        month: "Enero",
        year: 2023,
        nCampanias: 3,
        nTotalRecords: 100,
        nValidRecords: 80,
        nOpenedRecords: 60,
    },
    {
        month: "Febrero",
        year: 2023,
        nCampanias: 1,
        nTotalRecords: 100,
        nValidRecords: 40,
        nOpenedRecords: 30,
    },
    {
        month: "Marzo",
        year: 2023,
        nCampanias: 2,
        nTotalRecords: 100,
        nValidRecords: 80,
        nOpenedRecords: 60,
    },
    {
        month: "Abril",
        year: 2023,
        nCampanias: 3,
        nTotalRecords: 100,
        nValidRecords: 80,
        nOpenedRecords: 60,
    },
    {
        month: "Mayo",
        year: 2023,
        nCampanias: 4,
        nTotalRecords: 100,
        nValidRecords: 80,
        nOpenedRecords: 60,
    },
    {
        month: "Junio",
        year: 2023,
        nCampanias: 5,
        nTotalRecords: 100,
        nValidRecords: 80,
        nOpenedRecords: 60,
    },
    {
        month: "Julio",
        year: 2023,
        nCampanias: 3,
        nTotalRecords: 100,
        nValidRecords: 80,
        nOpenedRecords: 60,
    },
    {
        month: "Agosto",
        year: 2023,
        nCampanias: 3,
        nTotalRecords: 100,
        nValidRecords: 80,
        nOpenedRecords: 60,
    },
    {
        month: "Septiembre",
        year: 2023,
        nCampanias: 3,
        nTotalRecords: 100,
        nValidRecords: 80,
        nOpenedRecords: 60,
    },
    {
        month: "Octubre",
        year: 2023,
        nCampanias: 3,
        nTotalRecords: 100,
        nValidRecords: 80,
        nOpenedRecords: 60,
    },
    {
        month: "Noviembre",
        year: 2023,
        nCampanias: 3,
        nTotalRecords: 100,
        nValidRecords: 80,
        nOpenedRecords: 60,
    },
    {
        month: "Diciembre",
        year: 2023,
        nCampanias: 3,
        nTotalRecords: 100,
        nValidRecords: 80,
        nOpenedRecords: 60,
    },
];
