import { CampaniaMonthResult } from "@/Interfaces/CampaniaMonthResult";

export const data: CampaniaMonthResult[] = [
    {
        month: "Enero",
        year: 2023,
        nCampanias: 3,
        nTotalRecords: 100,
        nValidRecords: 80,
        nOpenedRecords: 60,
    },
    {
        month: "Febrero",
        year: 2023,
        nCampanias: 1,
        nTotalRecords: 100,
        nValidRecords: 40,
        nOpenedRecords: 30,
    },
    {
        month: "Marzo",
        year: 2023,
        nCampanias: 2,
        nTotalRecords: 100,
        nValidRecords: 80,
        nOpenedRecords: 60,
    },
    {
        month: "Abril",
        year: 2023,
        nCampanias: 3,
        nTotalRecords: 100,
        nValidRecords: 80,
        nOpenedRecords: 60,
    },
    {
        month: "Mayo",
        year: 2023,
        nCampanias: 4,
        nTotalRecords: 100,
        nValidRecords: 80,
        nOpenedRecords: 60,
    },
    {
        month: "Junio",
        year: 2023,
        nCampanias: 5,
        nTotalRecords: 100,
        nValidRecords: 80,
        nOpenedRecords: 60,
    },
    {
        month: "Julio",
        year: 2023,
        nCampanias: 3,
        nTotalRecords: 100,
        nValidRecords: 80,
        nOpenedRecords: 60,
    },
    {
        month: "Agosto",
        year: 2023,
        nCampanias: 3,
        nTotalRecords: 100,
        nValidRecords: 80,
        nOpenedRecords: 60,
    },
    {
        month: "Septiembre",
        year: 2023,
        nCampanias: 3,
        nTotalRecords: 100,
        nValidRecords: 80,
        nOpenedRecords: 60,
    },
    {
        month: "Octubre",
        year: 2023,
        nCampanias: 3,
        nTotalRecords: 100,
        nValidRecords: 80,
        nOpenedRecords: 60,
    },
    {
        month: "Noviembre",
        year: 2023,
        nCampanias: 3,
        nTotalRecords: 100,
        nValidRecords: 80,
        nOpenedRecords: 60,
    },
    {
        month: "Diciembre",
        year: 2023,
        nCampanias: 3,
        nTotalRecords: 100,
        nValidRecords: 80,
        nOpenedRecords: 60,
    },
];
